export  const menuData = [
  {
    "id":1,
    "Error_Rate": 1,
    "numOrder": 91,
    "OrderValue": 1559,
    "OrderVolume": 24,
    "Ratings": 3,
    "img": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGTB8X0lJN1Blpe9aos9c8-Oj7lZ0J_pDrgw&usqp=CAU",
  },
  {
    "Error_Rate": 2,
    "numOrder": 72,
    "OrderValue": 1265,
    "OrderVolume": 44,
    "Ratings": "4",
    "img": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUMIPLo3nKUf2vov2ku0tRcJq5qEI42iMq-Q&usqp=CAU",
  },
  {
    "Error_Rate": 1.5,
    "numOrder": 81,
    "OrderValue": 800,
    "OrderVolume": 34,
    "Ratings": "3",
    "img": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIK_KpHGeYHhCb_zRJ4VpW2sPD0z5Ym8Oa8g&usqp=CAU",
  },
  {
    "Error_Rate": 2.5,
    "numOrder": 51,
    "OrderValue": 450,
    "OrderVolume": 44,
    "Ratings": "2",
    "img": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIK_KpHGeYHhCb_zRJ4VpW2sPD0z5Ym8Oa8g&usqp=CAU",
  },
  {
    "Error_Rate": 1.5,
    "numOrder": 41,
    "OrderValue": 1700,
    "OrderVolume": 54,
    "Ratings": "1",
    "img": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUMIPLo3nKUf2vov2ku0tRcJq5qEI42iMq-Q&usqp=CAU",
  },
  {
    "Error_Rate": 2,
    "numOrder": 11,
    "OrderValue": 1900,
    "OrderVolume": 10,
    "Ratings": 3,
    "img": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGTB8X0lJN1Blpe9aos9c8-Oj7lZ0J_pDrgw&usqp=CAU",
  },
];
