export  const menuData = [
  {
    "id":1,
    "Error_Rate": 19,
    "numOrder": 91,
    "Order_value": 5599,
    "Order_volume": 44,
    "Ratings": 3,
    "img": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGTB8X0lJN1Blpe9aos9c8-Oj7lZ0J_pDrgw&usqp=CAU",
  },
  {
    "Error_Rate": 19,
    "numOrder": 72,
    "Order_value": 5599,
    "Order_volume": 44,
    "Ratings": 3,
    "img": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUMIPLo3nKUf2vov2ku0tRcJq5qEI42iMq-Q&usqp=CAU",
  },
  {
    "Error_Rate": 19,
    "numOrder": 81,
    "Order_value": 5599,
    "Order_volume": 44,
    "Ratings": 3,
    "img": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIK_KpHGeYHhCb_zRJ4VpW2sPD0z5Ym8Oa8g&usqp=CAU",
  },
  {
    "Error_Rate": 19,
    "numOrder": 51,
    "Order_value": 5599,
    "Order_volume": 44,
    "Ratings": 3,
    "img": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIK_KpHGeYHhCb_zRJ4VpW2sPD0z5Ym8Oa8g&usqp=CAU",
  },
  {
    "Error_Rate": 19,
    "numOrder": 41,
    "Order_value": 5599,
    "Order_volume": 44,
    "Ratings": 3,
    "img": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUMIPLo3nKUf2vov2ku0tRcJq5qEI42iMq-Q&usqp=CAU",
  },
  {
    "Error_Rate": 19,
    "numOrder": 11,
    "Order_value": 5599,
    "Order_volume": 44,
    "Ratings": 3,
    "img": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGTB8X0lJN1Blpe9aos9c8-Oj7lZ0J_pDrgw&usqp=CAU",
  },
];
